dist: trusty
sudo: false
language: c
compiler: gcc

addons:
  apt:
    update: true

before_install:
  - sudo apt-add-repository 'deb http://ppa.launchpad.net/anatol/tup/ubuntu precise main'
  - sudo apt-get update -q
  - sudo apt-get install -y libsdl2-dev python3 python3-dev tup

script: |
  python3 -m venv .env
  . .env/bin/activate
  python pip install --upgrade pip
  python pip install -r requirements.txt
  python pip install -t core/beer/python -r core/beer/python/requirements-game.txt
  python configure.py
  tup
